spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud
    username: study
    password: 1234

eureka:
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---

spring:
  config:
    activate:
      on-profile: eureka-1
  application:
    name: eureka-1
server:
  port: 8761
eureka:
  instance:
    hostname: eureka1.localhost.com

other:
  eureka:
    host: eureka2.localhost.com
    port: 8762

---

spring:
  config:
    activate:
      on-profile: eureka-2
  application:
    name: eureka-2
server:
  port: 8762
eureka:
  instance:
    hostname: eureka2.localhost.com

other:
  eureka:
    host: eureka1.localhost.com
    port: 8761