spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud
    username: study
    password: 1234


server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false #?? ??? ??? ?????? ???? ??
    register-with-eureka: false #?? ?????? ????? ??  ?? ??? ????? false???? ?? ?????? ?? ???
    service-url: #?? ??? ??? ???? ????? ??? ??? URL? Map? ???
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    #??? ??? ??? ????? ??? ???? ?? ?? ??? 30??? ???? ?????, ??? ???? ??? ?? ???? ???? ??? ???? ???? ?? ?? ????? ???.
    #?? ??????? ???? ??? ????? ??? ???. ?? ??????? ? ?? true? ?? ??? ???? ????? ?? ??? ??? ? ??
    #???, ???? ?? ???? ?????? ???? ????? ??? ??? ??? ??? ?? ??????.
    enable-self-preservation: false
