server:
  port: 0

eureka:
  client:
    service-url:
      # ?? ????? ????? 2?? ??? ??? ????? ?? ?? (??? ?? ?? ?, ???? ?? ??? ??)
      defaultZone: http://localhost:8761/eureka/,
#                    http://localhost2:8761/eureka/
spring:
  application:
    name: ingredient-service